# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\allis\OneDrive\Documents\GitHub\COMP4960-Money-Trackers\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1265, 727)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setGeometry(QtCore.QRect(30, 40, 111, 20))
        self.welcome_label.setObjectName("welcome_label")
        self.userchoice_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.userchoice_comboBox.setGeometry(QtCore.QRect(30, 70, 131, 28))
        self.userchoice_comboBox.setObjectName("userchoice_comboBox")
        self.userchoice_comboBox.addItem("")
        self.userchoice_comboBox.addItem("")
        self.userchoice_comboBox.addItem("")
        self.userchoice_comboBox.addItem("")
        self.userchoice_comboBox.addItem("")
        self.debt_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.debt_progressBar.setGeometry(QtCore.QRect(40, 570, 231, 41))
        self.debt_progressBar.setStyleSheet("background: rgb(153, 0, 3)")
        self.debt_progressBar.setProperty("value", 24)
        self.debt_progressBar.setInvertedAppearance(False)
        self.debt_progressBar.setObjectName("debt_progressBar")
        self.update_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.update_pushButton.setGeometry(QtCore.QRect(40, 630, 90, 29))
        self.update_pushButton.setObjectName("update_pushButton")
        self.transaction_tableView = QtWidgets.QTableView(self.centralwidget)
        self.transaction_tableView.setGeometry(QtCore.QRect(550, 60, 500, 500))
        self.transaction_tableView.setObjectName("transaction_tableView")
        self.transaction_label = QtWidgets.QLabel(self.centralwidget)
        self.transaction_label.setGeometry(QtCore.QRect(550, 30, 151, 20))
        self.transaction_label.setObjectName("transaction_label")
        self.tracking_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tracking_tabWidget.setGeometry(QtCore.QRect(550, 330, 361, 291))
        self.tracking_tabWidget.setObjectName("tracking_tabWidget")
        self.income_tab = QtWidgets.QWidget()
        self.income_tab.setAutoFillBackground(False)
        self.income_tab.setStyleSheet("background: rgb(255, 255, 255)\n"
"")
        self.income_tab.setObjectName("income_tab")
        self.tracking_tabWidget.addTab(self.income_tab, "")
        self.spending_tab = QtWidgets.QWidget()
        self.spending_tab.setObjectName("spending_tab")
        self.tracking_tabWidget.addTab(self.spending_tab, "")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setGeometry(QtCore.QRect(860, 0, 90, 29))
        self.logoutButton.setObjectName("logoutButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1265, 25))
        self.menubar.setObjectName("menubar")
        self.menuMoneyTracker = QtWidgets.QMenu(self.menubar)
        self.menuMoneyTracker.setObjectName("menuMoneyTracker")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMoneyTracker.menuAction())

        self.retranslateUi(MainWindow)
        self.tracking_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome user!"))
        self.userchoice_comboBox.setItemText(0, _translate("MainWindow", "-Select One-"))
        self.userchoice_comboBox.setItemText(1, _translate("MainWindow", "Add New File"))
        self.userchoice_comboBox.setItemText(2, _translate("MainWindow", "Manually Input Transactions"))
        self.userchoice_comboBox.setItemText(3, _translate("MainWindow", "Check Balance"))
        self.userchoice_comboBox.setItemText(4, _translate("MainWindow", "Savings Goals"))
        self.update_pushButton.setText(_translate("MainWindow", "update"))
        self.transaction_label.setText(_translate("MainWindow", "Recent Transactions:"))
        self.tracking_tabWidget.setTabText(self.tracking_tabWidget.indexOf(self.income_tab), _translate("MainWindow", "Tab 1"))
        self.tracking_tabWidget.setTabText(self.tracking_tabWidget.indexOf(self.spending_tab), _translate("MainWindow", "Tab 2"))
        self.logoutButton.setText(_translate("MainWindow", "Logout"))
        self.menuMoneyTracker.setTitle(_translate("MainWindow", "MoneyTracker"))
