# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\allis\OneDrive\Documents\GitHub\COMP4960-Money-Trackers\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1265, 727)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setObjectName("welcome_label")
        self.welcome_label.setText("Welcome user!")
        self.userchoice_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.userchoice_comboBox.setObjectName("userchoice_comboBox")
        self.userchoice_comboBox.addItems([
            "-Select One-",
            "Add New File",
            "Manually Input Transactions",
            "Check Balance",
            "Savings Goals"
        ])
        self.debt_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.debt_progressBar.setObjectName("debt_progressBar")
        self.debt_progressBar.setStyleSheet("background: rgb(153, 0, 3)")
        self.debt_progressBar.setProperty("value", 24)
        self.update_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.update_pushButton.setObjectName("update_pushButton")
        self.update_pushButton.setText("update")
        self.logoutButton = QtWidgets.QPushButton(self.centralwidget)
        self.logoutButton.setObjectName("logoutButton")
        self.logoutButton.setText("Logout")
        self.transaction_label = QtWidgets.QLabel(self.centralwidget)
        self.transaction_label.setObjectName("transaction_label")
        self.transaction_label.setText("Recent Transactions:")

        self.transaction_tableView = QtWidgets.QTableView(self.centralwidget)
        self.transaction_tableView.setObjectName("transaction_tableView")
        self.tracking_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tracking_tabWidget.setObjectName("tracking_tabWidget")
        self.income_tab = QtWidgets.QWidget()
        self.income_tab.setObjectName("income_tab")
        self.tracking_tabWidget.addTab(self.income_tab, "Income")
        self.spending_tab = QtWidgets.QWidget()
        self.spending_tab.setObjectName("spending_tab")
        self.tracking_tabWidget.addTab(self.spending_tab, "Spending")
        self.splitter = QtWidgets.QSplitter(QtCore.Qt.Vertical)
        self.splitter.addWidget(self.transaction_tableView)
        self.splitter.addWidget(self.tracking_tabWidget)
        self.right_panel_layout = QtWidgets.QVBoxLayout()
        self.right_panel_layout.addWidget(self.transaction_label)
        self.right_panel_layout.addWidget(self.splitter)
        self.right_panel_container = QtWidgets.QWidget(self.centralwidget)
        self.right_panel_container.setObjectName("right_panel_container")
        self.right_panel_container.setLayout(self.right_panel_layout)
        # Main layout
        self.main_layout = QtWidgets.QGridLayout(self.centralwidget)
        self.main_layout.addWidget(self.welcome_label, 0, 0)
        self.main_layout.addWidget(self.userchoice_comboBox, 1, 0)
        self.main_layout.addWidget(self.debt_progressBar, 2, 0)
        self.main_layout.addWidget(self.update_pushButton, 3, 0)
        self.main_layout.addWidget(self.logoutButton, 0, 2)
        self.main_layout.addWidget(self.right_panel_container, 1, 1, 3, 2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        self.menuMoneyTracker = QtWidgets.QMenu(self.menubar)
        self.menuMoneyTracker.setObjectName("menuMoneyTracker")
        self.menuMoneyTracker.setTitle("MoneyTracker")
        self.menubar.addAction(self.menuMoneyTracker.menuAction())
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.transaction_tableView.setStyleSheet("background-color: lightblue;")
        self.tracking_tabWidget.setStyleSheet("background-color: lightgreen;")