# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\allis\OneDrive\Documents\GitHub\COMP4960-Money-Trackers\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1323, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(190, 270, 90, 29))
        self.login_button.setObjectName("login_button")
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setGeometry(QtCore.QRect(300, 270, 111, 29))
        self.create_button.setObjectName("create_button")
        self.pw_box = QtWidgets.QLineEdit(self.centralwidget)
        self.pw_box.setGeometry(QtCore.QRect(200, 220, 201, 28))
        self.pw_box.setObjectName("pw_box")
        self.pass_label = QtWidgets.QLabel(self.centralwidget)
        self.pass_label.setGeometry(QtCore.QRect(200, 200, 81, 20))
        self.pass_label.setObjectName("pass_label")
        self.User_label = QtWidgets.QLabel(self.centralwidget)
        self.User_label.setGeometry(QtCore.QRect(200, 140, 81, 20))
        self.User_label.setObjectName("User_label")
        self.user_box = QtWidgets.QLineEdit(self.centralwidget)
        self.user_box.setGeometry(QtCore.QRect(200, 170, 201, 28))
        self.user_box.setObjectName("user_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1323, 25))
        self.menubar.setObjectName("menubar")
        self.menuMoney_Tracker = QtWidgets.QMenu(self.menubar)
        self.menuMoney_Tracker.setObjectName("menuMoney_Tracker")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMoney_Tracker.menuAction())
        self.menubar.addAction(self.menuLogin.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.create_button.setText(_translate("MainWindow", "Create Account"))
        self.pass_label.setText(_translate("MainWindow", "Password:"))
        self.User_label.setText(_translate("MainWindow", "Username:"))
        self.menuMoney_Tracker.setTitle(_translate("MainWindow", "Money  Tracker "))
        self.menuLogin.setTitle(_translate("MainWindow", "Login"))
